name: Android Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Configure Keystore
        run: |
          cd ./flutter/android
          echo "$ANDROID_KEYSTORE_FILE" > key.jks.b64
          base64 -d -i key.jks.b64 > app/key.jks
          echo "storeFile=key.jks" > key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          ls

        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Setup Build Config
        run: |
          touch local.properties
          echo "PIXABAY_KEY=$PIXABAY_KEY" >> local.properties
        env:
          PIXABAY_KEY: ${{ secrets.PIXABAY_KEY }}

      - name: Install bundle
        run: |
          gem install bundler
          bundle update --bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Distribute app to Alpha track 🚀
        run: |
          bundle exec fastlane deploy

      - name: Upload APK to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/app-release.apk

      - name: Upload AAB to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          asset_path: build/app/outputs/apk/app-release.apk
          asset_name: release.apk
          asset_content_type: application/zip
